In [4]:
import battleship as ship
import genetic_algorithm as ga

import pandas as pd
import numpy as np

In [2]:
#create a new board and solution
board, solution = ship.new_board()

# print the board
print(board)

# print the genetic solution
print(solution)

Correct number of pieces on board
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 1 0 1 1 1 1 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
0000000000000000000000000111100001000000010100000001011110000101000000001100000000100000000000000000


In [5]:
# initialize the first random generation
gene_pool = ga.random_generation(20, 100)
gene_pool

NameError: name 'np' is not defined

In [15]:
# compare fitness
gene_pool['Fitness'] = gene_pool.apply(lambda row: board_match(row.Phenotype, solution), axis=1)
gene_pool

Phenotype Generation   Birth  \
0   1100010111110110110110000001111000111000110011...          1  Random   
1   0010100001010101100100000100000100111000000011...          1  Random   
2   1010110100111011011011100110110000110010110001...          1  Random   
3   0100101101100000011011000011011110101100111111...          1  Random   
4   0010100110111101011011101000010100110001001000...          1  Random   
5   1001010111001111100010110110110110111011010101...          1  Random   
6   1101101110110111001001000011001100000111100101...          1  Random   
7   1110001000000010110100100110111000000010100100...          1  Random   
8   1110011000001111110100100111010011100110001101...          1  Random   
9   0000010000101101111110100010101000101110110010...          1  Random   
10  0000011010110000010000100111010010100110111011...          1  Random   
11  1100110001000000111010010001010000111101011101...          1  Random   
12  0100010100001101111110011111001010000001000111...          1  Random   
13  1001101011101101000110111101100101111101101011...          1  Random   
14  1000001101111001001011000100000011011111001011...          1  Random   
15  0101001000011001110011100111110101010100011001...          1  Random   
16  1000011101011001100001111001100110111101000010...          1  Random   
17  0111000001001000110010000011000010100010010110...          1  Random   
18  1001101010100110001000001100110011100111110101...          1  Random   
19  0001010000001100000101000110001001010110001011...          1  Random   

    Elite  Fitness  
0   False     0.45  
1   False     0.54  
2   False     0.42  
3   False     0.53  
4   False     0.54  
5   False     0.49  
6   False     0.53  
7   False     0.52  
8   False     0.46  
9   False     0.56  
10  False     0.46  
11  False     0.50  
12  False     0.59  
13  False     0.38  
14  False     0.55  
15  False     0.50  
16  False     0.53  
17  False     0.60  
18  False     0.52  
19  False     0.58

In [2]:
# select

In [3]:
# operate

In [4]:
# terminate

In [5]:
# heuristics