In [52]:
import battleship as ship
import genetic_algorithm as ga

import pandas as pd
import numpy as np

In [53]:
#create a new board and solution
board, solution = ship.new_board()

# print the board
print(board)

# print the genetic solution
print(solution)

Correct number of pieces on board
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 0 0 0 0]
 [0 1 1 0 0 1 0 0 0 0]
 [0 1 1 0 0 1 0 0 1 1]
 [0 0 1 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]]
0000000000000000000000000000000110010000011001000001100100110010010000001000000100000000010000000001


In [54]:
# initialize the first random generation
generation_size = 20
gene_pool = ga.random_generation(generation_size, 100)
gene_pool

Phenotype Generation   Birth  \
0   0000100100000011010100101111010110010110101011...          1  Random   
1   0010001110001110010101010011010000100100000011...          1  Random   
2   1001100000101101011111000110010010111001011000...          1  Random   
3   1000111110100001101101001110000000001011000001...          1  Random   
4   1001101000110001111011000110111001001000000010...          1  Random   
5   0111000110011000001100011110110011010100010001...          1  Random   
6   1000110100110010101101111001010111100110101010...          1  Random   
7   1110010101111110000011101110011101111100100001...          1  Random   
8   0100111000111111000110001101001101010100111110...          1  Random   
9   1000101100001100011100001001010011101101101001...          1  Random   
10  0011100100000111011110001011011001000100110001...          1  Random   
11  0010000100110100001000101110100110001010000110...          1  Random   
12  0011001101000011001100110100010101010110001001...          1  Random   
13  0100100011111100100011100100011010010110101001...          1  Random   
14  1011000010000000000111110001111001110001001101...          1  Random   
15  0110110010100100111011011111101100101011110001...          1  Random   
16  1010110111000010111101011000111101111110110110...          1  Random   
17  1110010010000100101100001001100100101000101111...          1  Random   
18  0101000110010111110100101001100011111000001001...          1  Random   
19  0010111100100111011110100111111101001011011011...          1  Random   

    Elite Fitness  
0   False     NaN  
1   False     NaN  
2   False     NaN  
3   False     NaN  
4   False     NaN  
5   False     NaN  
6   False     NaN  
7   False     NaN  
8   False     NaN  
9   False     NaN  
10  False     NaN  
11  False     NaN  
12  False     NaN  
13  False     NaN  
14  False     NaN  
15  False     NaN  
16  False     NaN  
17  False     NaN  
18  False     NaN  
19  False     NaN

In [57]:
# compare fitness
gene_pool['Fitness'] = gene_pool.apply(lambda row: ship.board_match(row.Phenotype, solution), axis=1)
gene_pool = gene_pool.sort_values(by='Fitness', ascending=False)

# identify elites
elite_rate = 0.2
elites = elite_rate * generation_size
gene_pool.iloc[0:int(elites),3:4] = True
gene_pool

Phenotype Generation   Birth  \
5   0111000110011000001100011110110011010100010001...          1  Random   
9   1000101100001100011100001001010011101101101001...          1  Random   
0   0000100100000011010100101111010110010110101011...          1  Random   
12  0011001101000011001100110100010101010110001001...          1  Random   
14  1011000010000000000111110001111001110001001101...          1  Random   
2   1001100000101101011111000110010010111001011000...          1  Random   
11  0010000100110100001000101110100110001010000110...          1  Random   
17  1110010010000100101100001001100100101000101111...          1  Random   
18  0101000110010111110100101001100011111000001001...          1  Random   
8   0100111000111111000110001101001101010100111110...          1  Random   
13  0100100011111100100011100100011010010110101001...          1  Random   
3   1000111110100001101101001110000000001011000001...          1  Random   
6   1000110100110010101101111001010111100110101010...          1  Random   
1   0010001110001110010101010011010000100100000011...          1  Random   
16  1010110111000010111101011000111101111110110110...          1  Random   
4   1001101000110001111011000110111001001000000010...          1  Random   
19  0010111100100111011110100111111101001011011011...          1  Random   
10  0011100100000111011110001011011001000100110001...          1  Random   
7   1110010101111110000011101110011101111100100001...          1  Random   
15  0110110010100100111011011111101100101011110001...          1  Random   

    Elite  Fitness  
5    True     0.64  
9    True     0.60  
0    True     0.58  
12   True     0.58  
14  False     0.57  
2   False     0.54  
11  False     0.54  
17  False     0.53  
18  False     0.52  
8   False     0.52  
13  False     0.51  
3   False     0.49  
6   False     0.48  
1   False     0.48  
16  False     0.47  
4   False     0.47  
19  False     0.45  
10  False     0.44  
7   False     0.43  
15  False     0.42

In [58]:
# select

In [3]:
# operate

In [4]:
# terminate

In [5]:
# heuristics