In [1]:
import battleship as ship
import genetic_algorithm as ga

import pandas as pd
import numpy as np

In [2]:
#create a new board and solution
board, solution = ship.new_board()

# print the board
print(board)

# print the genetic solution
print(solution)

Correct number of pieces on board
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 1 0 1 1 0 1 0 0 0]
 [0 1 0 1 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0]]
0000000000000010000000001000000000100000000110000001011010000101001000010000010001000001000000000100


In [3]:
# initialize the first random generation
generation_size = 20
gene_pool = ga.random_generation(generation_size, 100)

# compare fitness
gene_pool['Fitness'] = gene_pool.apply(lambda row: ship.board_match(row.Phenotype, solution), axis=1)

# assign elites with elite rate
elite_rate = 0.2
gene_pool = ga.assign_elites(gene_pool, elite_rate)

gene_pool

Sequence                                          Phenotype Generation  \
18       19  0001101100000011010000010111101000100111110010...          1   
8         9  0110001101111110000000101011001100000101000011...          1   
12       13  0100100001110101011100100101001000110100001011...          1   
19       20  0000101111011000101110000110001110001001010110...          1   
16       17  0111000101101111111101001100000101101010110110...          1   
17       18  0110100101000100000011000000100001110100111011...          1   
10       11  0010001001010011110000001100001111001110111111...          1   
5         6  1001000101010001101111100011100100110100010010...          1   
2         3  1101100011111010111011100101101000110100101011...          1   
13       14  0101001000001001101001110001111101111011101100...          1   
1         2  0110000010111001110001011111100100011110100001...          1   
11       12  0110111011110101010000110110011100001101101000...          1   
3         4  1001110111101010000111011011110110000111111111...          1   
0         1  1011110110000111001110111111101011101011010110...          1   
6         7  0101011101110101000011010101000100010000001101...          1   
15       16  1100101010010111010100110100001111001001100101...          1   
9        10  0111100100001001101000100000101010000100100111...          1   
14       15  0110110011110011111010101100010101011011110001...          1   
7         8  1010010101010110101000101111111100001001001001...          1   
4         5  1101111000100001111111110110111101111110100100...          1   

     Birth  Fitness  Elite  
18  Random     0.59   True  
8   Random     0.57   True  
12  Random     0.55   True  
19  Random     0.54   True  
16  Random     0.54  False  
17  Random     0.52  False  
10  Random     0.51  False  
5   Random     0.51  False  
2   Random     0.51  False  
13  Random     0.50  False  
1   Random     0.48  False  
11  Random     0.48  False  
3   Random     0.48  False  
0   Random     0.48  False  
6   Random     0.46  False  
15  Random     0.46  False  
9   Random     0.45  False  
14  Random     0.45  False  
7   Random     0.40  False  
4   Random     0.38  False

In [4]:
gene_pool.describe()

Fitness
count  20.000000
mean    0.493000
std     0.052626
min     0.380000
25%     0.460000
50%     0.490000
75%     0.525000
max     0.590000

In [5]:
# select elites with elite rate
next_generation = ga.select_elites(gene_pool)
next_generation

Sequence                                          Phenotype Generation  \
18        21  0001101100000011010000010111101000100111110010...          1   
8         22  0110001101111110000000101011001100000101000011...          1   
12        23  0100100001110101011100100101001000110100001011...          1   
19        24  0000101111011000101110000110001110001001010110...          1   

      Birth  Fitness  Elite Parent  
18  Elitism     0.59   True     19  
8   Elitism     0.57   True      9  
12  Elitism     0.55   True     13  
19  Elitism     0.54   True     20

In [ ]:
# operate
p = 0.2
n = 100
mutation_array = np.random.choice(2, 100, p=[0.8, 0.2])
sum(mutation_array)
#for i in mutation_array
#flip parent

In [ ]:
# terminate

In [ ]:
# heuristics